### ISSUE TITLE
CORREÇÃO 2 - FINAL

### ISSUE THREAD

**Issue by evssousa** [nicolasribeir12344/Fernando-De-Noronha#1]
Não existe link no about. Impossível correção.

**Comment by nicolasribeir12344** [comment]
Adicionado link no about

Em ter., 27 de fev. de 2024 às 08:39, Everson Sousa <
***@***.***> escreveu:

**Comment by nicolasribeir12344** [comment]
Correção finalizada

Em ter., 27 de fev. de 2024 às 08:39, Everson Sousa <
***@***.***> escreveu:
